CLIENT-76: fixed and improved pre-commit hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
-echo "pre commit hook"
+echo "pre-commit hook"
 sh scripts/eslint.sh || exit 1
 if grep -r -i 'TODO!' ./src
-  then echo "Cant commit with TODO!" && exit 1
+  then echo "Can't commit with TODO!" && exit 1
 fi
-echo "pre commit hook >> DONE"
+if grep -r -i 'debugger' ./src
+  then echo "Can't commit with debugger" && exit 1
+fi
+echo "pre-commit hook >> DONE"
 
 exit 0
